FROM node:12-alpine

WORKDIR /app
COPY ./client/package.json /app/package.json
RUN npm install --production
COPY ./client/. /app
RUN npm run build

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN chmod +x /wait

CMD /wait && npm run server
